export { TerminalContainer } from './TerminalContainer'
export type { TerminalContainerHandle } from './TerminalContainer'
export { TerminalTabBar, MODE_ICONS } from './TerminalTabBar'
export type { TerminalTabBarHandle } from './TerminalTabBar'
export { TerminalSplitGroup } from './TerminalSplitGroup'
export { useTaskTerminals } from './useTaskTerminals'
export { ChatPanel } from './chat/ChatPanel'
export type { ChatPanelProps } from './chat/ChatPanel'
export { CHAT_SUPPORTED_MODES, isChatSupported } from '../shared/chat-modes'
